[package]
name = "server"
version = "0.1.0"
authors = ["Samuel Sleight <samuel.sleight@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.4"
rocket_contrib = "0.4.4"
structopt = { version = "0.3.14", features = ["paw"] }
paw = "1.0.0"
